import et from "../assets/et.jpg";
import ch from "../assets/ch.jpg";
import sp from "../assets/sp.jpg";
import bb from "../assets/bb.jpg";
import vh from "../assets/vh.jpg";
import sw from "../assets/sw.png";
import ex from "../assets/ex.png";
import wa from "../assets/wa.jpg";

const roomData = [
	{
		name: "Egyptian Tomb",
		img: et,
		desc: "You and an intrepid team of archaeologists must enter an Egyptian tomb that’s been sealed since the 1940s. Your mission? To find information on a famed archaeologist who hasn’t been seen since entering the tomb decades ago.",
		escapeRate: 35.3,
		recordTime: 39.32,
		averageTime: 48.55,
		price: 35,
		link: "/rooms/egyptian-tomb",
		booking: "/et-booking.html",
		players: 8,
		location: "Convention Center",
		points: 0,
		appeals: ["kids", "Small Groups", "Beginners"],
		longDesc: [
			"It’s the 1940s. A famed archeologist disappears inside a tomb without a trace during an excavation. Eight decades later, it’s now up to you and your team to determine his fate and avoid becoming trapped in the Egyptian Tomb.",
			"Lovers of historical artifacts and Egyptology have much to look forward to when visiting EscapeWorks Denver. In addition to our complex puzzles and captivating clues, we also put a lot of effort into developing compelling themes. You’ll be wowed by the look of the place, but only momentarily, as you must solve the puzzle and make your escape in 60 minutes or less.",
			"This room is perfect for new players, as well as teens and families. The following Ancient Egypt facts can also add a bit of history to your experience:",
		],
		facts: [
			"Pharaohs were buried with their treasure inside tombs",
			"More than 130 pyramids have been discovered in Egypt",
			"Cats were considered sacred in Ancient Egypt",
			"The Ancient Egyptian alphabet consisted of hieroglyphs",
		],
	},
	{
		name: "Blackbeard's Brig",
		img: bb,
		desc: "On the hunt for Blackbeard the Pirate, you find yourself captured by the dastardly scoundrel and thrown into the ship’s brig. Now you must escape the brig and take the helm to sail away to freedom, with your booty in tow.",
		escapeRate: 45.8,
		recordTime: 36.05,
		averageTime: 54.29,
		price: 35,
		link: "/rooms/blackbeards-brig",
		booking: "/bb-booking.html",
		players: 12,
		location: "Convention Center",
		points: 0,
		appeals: ["kids", "Large Groups", "Birthday Parties"],
		longDesc: [
			"During the 1700s, Blackbeard the pirate was notorious for his many fearsome battles on the high seas. The legendary exploits of Blackbeard persist to this day, where his spirit is alive and well at EscapeWorks Denver.",
			"We put a lot of care and consideration into our room themes, and Blackbeard’s Brig is no exception. Like our other rooms, you and your team will be faced with complex puzzles and mysterious clues, which are your key to escaping the brig and securing freedom. You’ll have just one hour to make your daring escape, after which you’ll be left to the mercy of Blackbeard and his formidable crew if you’re unsuccessful.",
			"We recommend this room for large groups and families. We also offer the following tips to get the most out of the experience:",
		],
		facts: [
			"Choose your team wisely",
			"Be vocal when you happen upon clues",
			"Don’t spend too much time on a puzzle; if you’re confused, get help",
			"Contribute as much as possible",
			"Organize clues and objects as you find them",
			"Follow the instructions you’re provided",
			"Most importantly, have fun",
		],
	},
	{
		name: "Vampire Hunter",
		img: vh,
		desc: "In EscapeWorks Denver’s newest (and most immersive) game room debut, ancient evil has been awakened in a town cemetery. Those who go outside after sunset, never return home.",
		escapeRate: 31.3,
		recordTime: 32.48,
		averageTime: 42.55,
		price: 38,
		link: "/rooms/vampire-hunter",
		booking: "/vh-booking.html",
		players: 8,
		location: "Convention Center",
		points: 0,
		appeals: ["Experienced Players", "Small Groups", "Horror Fans"],
		longDesc: [
			"The Vampire Hunter room is a thrilling and immersive experience that will transport you to a town cemetery where ancient evil has been awakened.",
			"You and your team will have 60 minutes to solve puzzles and clues to escape the room before the sun sets and the vampires come outs to play.",
			"This room is perfect for experienced players, as well as horror fans and small groups.",
		],
		facts: [
			"The first vampire movie was Nosferatu in 1922",
			"The first vampire book The Vampyre, was published in 1819",
			"The word vampire first appeared in English in 1734",
			"The vampire myth is present in almost every culture around the world",
		],
	},
	{
		name: "Speakeasy",
		img: sp,
		desc: "Take a trip back in time to 1926, the prohibition era. While alcohol is illegal, crime is on the rise in the form of back-alley deals, police collusion, and mobsters ruling the town. You see an innocent looking flower shop, but is it really what it seems?",
		escapeRate: 41.9,
		recordTime: 33.38,
		averageTime: 50.22,
		price: 35,
		link: "/rooms/speakeasy",
		booking: "/sp-booking.html",
		players: 12,
		location: "Convention Center",
		points: 0,
		appeals: ["Bach Parties", "Large Groups", "Familiar Players"],
		longDesc: [
			`
		It’s 1926 and the US is in the midst of prohibition. You find yourself in front of a flower shop, which looks about as innocuous as they come. But is it all that it seems? Is this one of those speakeasies you’ve heard so much about? And do you have what it takes to go inside?`,
			"EscapeWorks Denver transports you to a bygone era with The Speakeasy. You and your team will have 60 minutes to hunt for clues to help you solve puzzles, evade crooks, and keep the cops off your back. All within the smokey backdrop of a rough and tumble gin joint.",
			"The Speakeasy is perfect for parties, as well as corporate groups. It’s also a great homage to the prohibition era, which is a time period rife with historical importance:",
		],
		facts: [
			"It was still legal to drink in your own home during prohibition",
			"Prohibition was integral in the creation of non-alcoholic beer containing less than 0.5% alcohol",
			"There were over 30,000 speakeasies in New York City in the 1920s",
			"Certain counties throughout the US continue to ban alcohol to this day",
		],
	},
	{
		name: "Casino Heist",
		img: ch,
		desc: "Our Casino Heist room gives you a taste of what it’s like to be double-crossed. After months of meticulous planning, the mastermind of the heist decides to go it alone.",
		escapeRate: 28.2,
		recordTime: 31.1,
		averageTime: 51.12,
		price: 35,
		link: "/rooms/casino-heist",
		booking: "/ch-booking.html",
		players: 8,
		location: "Convention Center",
		points: 0,
		appeals: ["Bach Parties", "Small Groups", "Experienced Players"],
		longDesc: [
			"Now you’re embroiled in a thrilling Casino Heist courtesy of EscapeWorks Denver. Test your wits and wills against our complex puzzles to escape before time runs out. If you’re successful within 60 minutes or less.",
			"You’ll get to escape with your freedom and with the profits in tow. If not, you’ll be cooling your heels in a federal prison for years to come.",
			"Casino Heist requires a high level of skill, so we recommend it for experienced players. It’s also a great place for wedding proposals! While you’re working through puzzles and clues, keep these casino facts in mind:",
		],
		facts: [
			"All the numbers of a roulette wheel add up to 666",
			"The biggest Las Vegas casino win ever involved a $39.7 million jackpot",
			"Surprisingly, card counting is not illegal",
			"Penny slot machines are the biggest earners in most casinos",
			"A person once stole $1.5 million in chips from the Bellagio",
		],
	},
	{
		name: "Space Wars",
		img: sw,
		desc: "Embark on a thrilling space escapade! Board the enemy ship, rescue the prisoners, and become a hero of the Galactic Alliance!",
		escapeRate: 28.2,
		recordTime: 31.1,
		averageTime: 51.12,
		price: 38,
		link: "/rooms/space-wars",
		players: 12,
		location: "Ballpark",
		points: 0,
		appeals: ["Experienced Players", "Large Groups", "Sci-Fi Fans"],
	},
	{
		name: "The Exorcism",
		img: ex,
		desc: "The Doctors and his daughter have disappeared. Rumors have it, they have succumb to demonic spirits.",
		escapeRate: 28.2,
		recordTime: 31.1,
		averageTime: 51.12,
		price: 38,
		link: "/rooms/the-exorcism",
		players: 8,
		location: "Ballpark",
		points: 0,
		appeals: ["Horror Fans", "Small Groups", "Familiar Players"],
	},
	{
		name: "Wizard's Alley",
		img: wa,
		desc: "Your feline friend has ran away from home and into the mysterious Wizard's Alley. Be warned: sinister magic is around every corner.",
		escapeRate: 28.2,
		recordTime: 31.1,
		averageTime: 51.12,
		price: 38,
		link: "/rooms/wizards-alley",
		players: 12,
		location: "Ballpark",
		points: 0,
		appeals: ["Birthday Parties", "Large Groups", "Kids"],
	},
];

export default roomData;
